// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDgHV9mBESDQQw4NaUOTkwG_AGHjsSgKmQ',
    appId: '1:793926793023:web:38e2a7857292d22621058a',
    messagingSenderId: '793926793023',
    projectId: 'arrhythmia-e91bf',
    authDomain: 'arrhythmia-e91bf.firebaseapp.com',
    storageBucket: 'arrhythmia-e91bf.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyANv61HfiXtWSaSZhDzimmDKVpBI9hBcUU',
    appId: '1:793926793023:android:54cb43295ae6a52421058a',
    messagingSenderId: '793926793023',
    projectId: 'arrhythmia-e91bf',
    storageBucket: 'arrhythmia-e91bf.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBKcEVXm_tv6uAZ5FZ1tqgQ5-f88RxbxQU',
    appId: '1:793926793023:ios:724e8a6f87c0374b21058a',
    messagingSenderId: '793926793023',
    projectId: 'arrhythmia-e91bf',
    storageBucket: 'arrhythmia-e91bf.appspot.com',
    iosBundleId: 'com.example.rhythmia',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBKcEVXm_tv6uAZ5FZ1tqgQ5-f88RxbxQU',
    appId: '1:793926793023:ios:724e8a6f87c0374b21058a',
    messagingSenderId: '793926793023',
    projectId: 'arrhythmia-e91bf',
    storageBucket: 'arrhythmia-e91bf.appspot.com',
    iosBundleId: 'com.example.rhythmia',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDgHV9mBESDQQw4NaUOTkwG_AGHjsSgKmQ',
    appId: '1:793926793023:web:de298dbf193de8ac21058a',
    messagingSenderId: '793926793023',
    projectId: 'arrhythmia-e91bf',
    authDomain: 'arrhythmia-e91bf.firebaseapp.com',
    storageBucket: 'arrhythmia-e91bf.appspot.com',
  );
}
